blank_issues_enabled: true
contact_links:
  - name: Commonwealth Discussions
    url: https://commonwealth.im/evmos/
    about: Join the discussions revolving around Governance on Commonwealth  
    
  - name: Evmos Discord
    url: https://discord.gg/evmos
    about: Join the discussions revolving around Governance on Discord