name: New Governance Issue
description: File a governance related issue
title: '<title>'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this governance issue! The more info you provide, the more we can help.

  - type: textarea
    attributes:
      label: 🚧 The Issue, Concern, or Problem
      description: A concise description of what the problem in our governance.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ Possible Solutions
      description: If you have ideas on how this issue can be solved, please share!
    validations:
      required: false

  - type: input
    attributes:
      label: 🌐 Link to Commonwealth Discussion
      description: |
        If this issue has been talked about on Commonwealth, please link to the thread for reference.
      placeholder: https://commonwealth.im/evmos/...
    validations:
      required: false

  - type: input
    attributes:
      label: 🌐 Other Relevant Link
      description: |
        If there is another link you would like to submit, please do so here.
      placeholder: https://twitter.com/evmosorg/...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        💡 Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
      
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
